project:
  type: website 
  output-dir: docs
  resources:
  - CNAME

website:
  title: "danduncan.dev"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - cv.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



